name:                solar
version:             0.1.0.0
github:              "montmorency/solar"
license:             BSD3
author:              "Henry Lambert"
maintainer:          "lamberh@tcd.ie"
copyright:           "2020 Henry Lambert"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/montmorency/solar#readme>

dependencies:
- base >= 4.7 && < 5
- units
- units-defs
- wreq  

library:
  source-dirs: src

executables:
  solar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solar
    - units
    - units-defs
    - wreq  

tests:
  solar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solar
